### PR TITLE
add candlestick dataset options types

### LINKED ISSUE #114: Candle border options
Enhancement recommendation: on a chart with many candles, I would like the red and green colors to be prevalent.  With excess bars, the colors completely disappear.  Recommend either 1) have border options, or 2) default to borderless candles where wicks, border, and body are one color.

Current:
4A57A580-7C16-4828-9CDB-9FDB26FB3D69

Preferred:
37ECC201-E02B-4615-AACF-261228B16EC8

### PR DESCRIPTION
**Pull request by DaveSkender**
- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://developercertificate.org)

## Description

Fixes #114 

Adding custom `CandlestickControllerDatasetOptions` typings to replace use of `BarControllerDatasetOptions` to allow for unique `borderColor` type:

```typescript
borderColor: {
  up: string,
  down: string,
  unchanged: string
};
```

This will allow the configuration of bar color properties in Typescript/Angular sites where typings are needed.  For example:

image

```typescript
// sample usage

let candleOptions = Chart.defaults.elements["candlestick"];

// sets body color
candleOptions.color.up = 'blue';
candleOptions.color.down = 'orange';

myConfig.data = {
  datasets: [
    {
      type: 'candlestick',
      label: 'Price',
      data: price,
      borderColor: {  // set border and wicks color
        up: candleOptions.color.up,
        down: candleOptions.color.down,
        unchanged: candleOptions.color.unchanged
      },
      yAxisID: 'yAxis'
    }
  ]
};
```

## Additional comments

I'm not a JS expert, so please treat this as a suggestion.  There may be a better way to handle it.  This approach seems to be a bit of a hack.  I have two other suggestions here:

1. Make this the default so you'd only need to provide `borderColor` if you wanted a consistently colored border.

   ```typescript
    borderColor: {
      up: candleOptions.color.up,
      down: candleOptions.color.down,
      unchanged: candleOptions.color.unchanged
    }
   ```

2. Allow use of `backgroundColor` in a similar up/down/unchanged format.  Overriding `Chart.defaults.elements["candlestick"]` as shown in my example (above) is less intuitive.

### CODE REVIEW

**Comment by superdavid0816** [comment]
Hi, 

I read your 2 articles about candle stick color.
"add candlestick dataset options types #115"
"Candle border options #114"


my library is 
Chart.js 
and ng2-chart 
and Chart.js Financial Charting

I just installed these package in these days.

sample page if from here:
https://valor-software.com/ng2-charts/#FinancialChart

I try to follow your step to create my color in candle stick.
I paste this line and get error.

const candleOptions = Chart.defaults.elements["candlestick"];

error:
Property 'candlestick' does not exist on type 'ElementOptionsByType<keyof ChartTypeRegistry>'.ts(7053)

I think that might be caused by version of the package.

Do you know how to fix this?

I saw you can make the candle into orange and blue.
That's great. I want to change my candle color.

Thank you.

**Comment by DaveSkender** [comment]
My last entry n 12/30/2021 in #114 has the workaround that used to get it to compile correctly with the kissing typings.

You can also [see the code](https://github.com/DaveSkender/Stock.Charts/tree/main/Client/src/app/chart) for [this demo charting site](https://charts.stockindicators.dev/) to see it fully implemented.

**Comment by superdavid0816** [comment]
@DaveSkender 
Your program is amazing!
Thanks for your code.
I will read it line by line.
Thank you very much.

**Comment by Kharabet** [comment]
@DaveSkender why did you close this PR?

**Comment by DaveSkender** [comment]
> @DaveSkender why did you close this PR?

Deleting my fork auto-closed it.  It wasn’t purely intentional, I suspect I was just cleaning out my old forks.  This was sitting idle for a long time.

**Comment by Kharabet** [comment]
@etimberg whom we should ping to take a look at the above issue?

**Comment by Kharabet** [comment]
cc @benmccann ^

**Comment by etimberg** [comment]
@Kharabet either @santam85 or @benmccann as they were the maintainers of this

**Comment by DaveSkender** [comment]
> @Kharabet @DaveSkender sorry missed this completely, happy to merge this definitely needed improvement, hopefully the release pipeline still works 🤞

Cool.  I've put in a GitHub ticket to restore my fork, but will otherwise recreate this PR if that approach fails.  May take a few days.

**Pull request closed without merging**
